publisher_scaled_joint_trajectory_controller:
  ros__parameters:

    controller_name: "scaled_joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["degree145", "degree150", "degree155", "degree160", "degree165", "degree170", "degree175", "degree180"]
    degree145:
      positions: [-41.72, -59.86, 130.28, -160.45, -89.81, 48.95]
    degree150:
      positions: [-41.06, -57.65, 124.63, -157.0, -89.79, 49.61]
    degree155:
      positions: [-40.15, -55.27, 118.81, -153.58, -89.77, 50.51]
    degree160:
      positions: [-39.06, -52.73, 112.85, -150.15, -89.76, 51.6]
    degree165:
      positions: [-37.81, -50.08, 106.76, -146.71, -89.74, 52.83]
    degree170:
      positions: [-36.43, -47.3, 100.51, -143.2, -89.72, 54.19]
    degree175:
      positions: [-34.96, -44.41, 94.1, -139.72, -89.7, 55.56]
    degree180:
      positions: [-33.4, -41.41, 87.53, -136.16, -89.7, 57.2]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]

publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 6

    goal_names: ["degree145", "degree150", "degree155", "degree160", "degree165", "degree170", "degree175", "degree180"]
    degree145:
      positions: [-41.72, -59.86, 130.28, -160.45, -89.81, 48.95]
    degree150:
      positions: [-41.06, -57.65, 124.63, -157.0, -89.79, 49.61]
    degree155:
      positions: [-40.15, -55.27, 118.81, -153.58, -89.77, 50.51]
    degree160:
      positions: [-39.06, -52.73, 112.85, -150.15, -89.76, 51.6]
    degree165:
      positions: [-37.81, -50.08, 106.76, -146.71, -89.74, 52.83]
    degree170:
      positions: [-36.43, -47.3, 100.51, -143.2, -89.72, 54.19]
    degree175:
      positions: [-34.96, -44.41, 94.1, -139.72, -89.7, 55.56]
    degree180:
      positions: [-33.4, -41.41, 87.53, -136.16, -89.7, 57.2]

    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    check_starting_point: false
    starting_point_limits:
      shoulder_pan_joint: [-0.1,0.1]
      shoulder_lift_joint: [-1.6,-1.5]
      elbow_joint: [-0.1,0.1]
      wrist_1_joint: [-1.6,-1.5]
      wrist_2_joint: [-0.1,0.1]
      wrist_3_joint: [-0.1,0.1]
